// Mocks generated by Mockito 5.0.5 from annotations
// in flutter_bloc_simple_demo/test/unit/weather_bloc_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i6;

import 'package:flutter_bloc_simple_demo/data/weather_repo.dart' as _i5;
import 'package:flutter_bloc_simple_demo/models/weather_model.dart' as _i3;
import 'package:http/src/client.dart' as _i2;
import 'package:http/src/response.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: comment_references
// ignore_for_file: unnecessary_parenthesis

class _FakeClient extends _i1.Fake implements _i2.Client {}

class _FakeWeatherModel extends _i1.Fake implements _i3.WeatherModel {}

class _FakeResponse extends _i1.Fake implements _i4.Response {}

/// A class which mocks [WeatherRepo].
///
/// See the documentation for Mockito's code generation for more information.
class MockWeatherRepo extends _i1.Mock implements _i5.WeatherRepo {
  MockWeatherRepo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Client get client => (super.noSuchMethod(Invocation.getter(#client),
      returnValue: _FakeClient()) as _i2.Client);
  @override
  set client(_i2.Client? _client) =>
      super.noSuchMethod(Invocation.setter(#client, _client),
          returnValueForMissingStub: null);
  @override
  _i6.Future<_i3.WeatherModel?> getWeather(String? city) =>
      (super.noSuchMethod(Invocation.method(#getWeather, [city]),
              returnValue: Future<_i3.WeatherModel?>.value(_FakeWeatherModel()))
          as _i6.Future<_i3.WeatherModel?>);
  @override
  String formatCity(String? city) => (super
          .noSuchMethod(Invocation.method(#formatCity, [city]), returnValue: '')
      as String);
  @override
  _i6.Future<_i4.Response> getLocationResponse(String? city) =>
      (super.noSuchMethod(Invocation.method(#getLocationResponse, [city]),
              returnValue: Future<_i4.Response>.value(_FakeResponse()))
          as _i6.Future<_i4.Response>);
  @override
  int findWoeid(_i4.Response? locationResponse) =>
      (super.noSuchMethod(Invocation.method(#findWoeid, [locationResponse]),
          returnValue: 0) as int);
  @override
  _i6.Future<_i4.Response> getWeatherResponse(dynamic woeid) =>
      (super.noSuchMethod(Invocation.method(#getWeatherResponse, [woeid]),
              returnValue: Future<_i4.Response>.value(_FakeResponse()))
          as _i6.Future<_i4.Response>);
}
